[package]
name = "yoink"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
clap = { version = "4.5", features = ["derive"] }
globset = "0.4"
regex = "1.11"
walkdir = "2.5"
which = "7.0"

[dev-dependencies]
tempfile = "3.16"
